### ISSUE TITLE
open_appliedcv died! 'seek_req_val'

### ISSUE THREAD

**Issue by AccelQuasarDragon** [ShootingStarDragon/FastCVApp#426]
- [ ] not fixed, on loop, it happens again: 
```
open_appliedcv died! 'seek_req_val'
full exception Traceback (most recent call last):
  File "fastcvapp\fastcvapp.py", line 753, in open_cvpipeline
  File "<string>", line 2, in __getitem__
  File "multiprocessing\managers.py", line 825, in _callmethod
KeyError: 'seek_req_val'
```
- [x] i don't see the problem anymore....
- [x] fixed already, the bug is when u play w/o using mouse to seek, so in that case add that key to the dict
```
if "seek_req_val" not in temp_override_list:
    temp_override_list += "seek_req_val"
```
- [x] on repeat: 
```
open_appliedcv died! 'seek_req_val'
full exception Traceback (most recent call last):
  File "fastcvapp\fastcvapp.py", line 743, in open_cvpipeline
  File "<string>", line 2, in __getitem__
  File "multiprocessing\managers.py", line 825, in _callmethod
KeyError: 'seek_req_val'
```
- [x] possible errors:
	- [x] seek_req_val not set correctly on repeat
	- [x] clicked wrong? idk (so button isn't working right? i dont think so)
	- [x] when do i clear seek_req_val?
	- [x] maybe it's not set in the first place since i press play and didnt seek
		- [x] TEST: 
			- [x] press play and it bugs out
			- [x] seek and then check it out > runs right OK found the bug
- [x] EZ Fix:
- [x] when u press play, set seek_req_val to the beginning (value of 0)
- [x] ANOTHER BUG: 
- [x] play button is just broken, it doesn't even pause

**Comment by AccelQuasarDragon** [comment]
solved, just check if key in .keys() before looking it up
